version: "3"
services:
  stress-test:
    image: stress-test:1.0.0
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '128m'