apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o kubernetes
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: stress-test
  name: stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stress-test
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -o kubernetes
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: stress-test
    spec:
      containers:
      - image: stress-test:1.0.0
        imagePullPolicy: ""
        name: stress-test
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "250m"
            memory: "192Mi"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null