apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stress-test
spec:
  minReplicas: 5
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-test
  targetCPUUtilizationPercentage: 50