apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: "stress-test"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "stress-test"
  template:
    metadata:
      labels:
        app: "stress-test"
    spec:
      containers:
      - image: "stress-test:1.0.0"
        name: "stress-test"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "250m"
            memory: "192Mi"
      restartPolicy: Always