apiVersion: v1
kind: Service
metadata:
  name: "stress-test"
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: 8080-tcp
      nodePort: 30929
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: "stress-test"
  sessionAffinity: None
  type: LoadBalancer
